import { NetworkConfig } from '@/types';

// DEX router addresses (PancakeSwap V2 / Uniswap V2 forks)
export const DEX_ROUTERS: Record<string, string> = {
  ethereum:       '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D', // Uniswap V2
  sepolia:        '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D', // Uniswap V2 (Sepolia)
  bsc:            '0x10ED43C718714eb63d5aA57B78B54704E256024E', // PancakeSwap V2
  'bsc-testnet':  '0xD99D1c33F9fC3444f8101754aBC46c52416550D1', // PancakeSwap V2 Testnet
  polygon:        '0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff', // QuickSwap
  'polygon-amoy': '0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff',
  avalanche:      '0x60aE616a2155Ee3d9A68541Ba4544862310933d4', // TraderJoe
  arbitrum:       '0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506', // SushiSwap
  optimism:       '0x4A7b5Da61326A6379179b40d00F57E5bbDC962c2', // Velodrome
};

export const NETWORKS: Record<string, NetworkConfig> = {
  ethereum: {
    id: 1,
    name: 'Ethereum Mainnet',
    shortName: 'ethereum',
    symbol: 'ETH',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_ETHEREUM_RPC || 'https://eth.llamarpc.com',
    explorerUrl: 'https://etherscan.io',
    explorerApiUrl: 'https://api.etherscan.io/api',
    isTestnet: false,
    icon: '⟠',
    color: '#627EEA',
    isEVM: true,
    chainType: 'evm',
  },
  sepolia: {
    id: 11155111,
    name: 'Sepolia Testnet',
    shortName: 'sepolia',
    symbol: 'ETH',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_ETHEREUM_TESTNET_RPC || 'https://rpc.sepolia.org',
    explorerUrl: 'https://sepolia.etherscan.io',
    explorerApiUrl: 'https://api-sepolia.etherscan.io/api',
    faucetUrl: 'https://sepoliafaucet.com',
    isTestnet: true,
    icon: '⟠',
    color: '#627EEA',
    isEVM: true,
    chainType: 'evm',
  },
  bsc: {
    id: 56,
    name: 'BNB Smart Chain',
    shortName: 'bsc',
    symbol: 'BNB',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_BSC_RPC || 'https://bsc-dataseed1.binance.org',
    explorerUrl: 'https://bscscan.com',
    explorerApiUrl: 'https://api.bscscan.com/api',
    isTestnet: false,
    icon: '⬡',
    color: '#F3BA2F',
    isEVM: true,
    chainType: 'evm',
  },
  'bsc-testnet': {
    id: 97,
    name: 'BSC Testnet',
    shortName: 'bsc-testnet',
    symbol: 'tBNB',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_BSC_TESTNET_RPC || 'https://data-seed-prebsc-1-s1.binance.org:8545',
    explorerUrl: 'https://testnet.bscscan.com',
    explorerApiUrl: 'https://api-testnet.bscscan.com/api',
    faucetUrl: 'https://testnet.binance.org/faucet-smart',
    isTestnet: true,
    icon: '⬡',
    color: '#F3BA2F',
    isEVM: true,
    chainType: 'evm',
  },
  polygon: {
    id: 137,
    name: 'Polygon Mainnet',
    shortName: 'polygon',
    symbol: 'MATIC',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_POLYGON_RPC || 'https://polygon.llamarpc.com',
    explorerUrl: 'https://polygonscan.com',
    explorerApiUrl: 'https://api.polygonscan.com/api',
    isTestnet: false,
    icon: '⬡',
    color: '#8247E5',
    isEVM: true,
    chainType: 'evm',
  },
  'polygon-amoy': {
    id: 80002,
    name: 'Polygon Amoy Testnet',
    shortName: 'polygon-amoy',
    symbol: 'MATIC',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_POLYGON_TESTNET_RPC || 'https://rpc-amoy.polygon.technology',
    explorerUrl: 'https://www.oklink.com/amoy',
    faucetUrl: 'https://faucet.polygon.technology',
    isTestnet: true,
    icon: '⬡',
    color: '#8247E5',
    isEVM: true,
    chainType: 'evm',
  },
  avalanche: {
    id: 43114,
    name: 'Avalanche C-Chain',
    shortName: 'avalanche',
    symbol: 'AVAX',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_AVALANCHE_RPC || 'https://api.avax.network/ext/bc/C/rpc',
    explorerUrl: 'https://snowtrace.io',
    explorerApiUrl: 'https://api.snowtrace.io/api',
    isTestnet: false,
    icon: '△',
    color: '#E84142',
    isEVM: true,
    chainType: 'evm',
  },
  arbitrum: {
    id: 42161,
    name: 'Arbitrum One',
    shortName: 'arbitrum',
    symbol: 'ETH',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_ARBITRUM_RPC || 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io',
    explorerApiUrl: 'https://api.arbiscan.io/api',
    isTestnet: false,
    icon: '◈',
    color: '#28A0F0',
    isEVM: true,
    chainType: 'evm',
  },
  optimism: {
    id: 10,
    name: 'Optimism',
    shortName: 'optimism',
    symbol: 'ETH',
    decimals: 18,
    rpcUrl: process.env.NEXT_PUBLIC_OPTIMISM_RPC || 'https://mainnet.optimism.io',
    explorerUrl: 'https://optimistic.etherscan.io',
    explorerApiUrl: 'https://api-optimistic.etherscan.io/api',
    isTestnet: false,
    icon: '⬤',
    color: '#FF0420',
    isEVM: true,
    chainType: 'evm',
  },
  solana: {
    id: 'solana-mainnet',
    name: 'Solana Mainnet',
    shortName: 'solana',
    symbol: 'SOL',
    decimals: 9,
    rpcUrl: process.env.NEXT_PUBLIC_SOLANA_RPC || 'https://api.mainnet-beta.solana.com',
    explorerUrl: 'https://solscan.io',
    isTestnet: false,
    icon: '◎',
    color: '#9945FF',
    isEVM: false,
    chainType: 'solana',
  },
  'solana-devnet': {
    id: 'solana-devnet',
    name: 'Solana Devnet',
    shortName: 'solana-devnet',
    symbol: 'SOL',
    decimals: 9,
    rpcUrl: process.env.NEXT_PUBLIC_SOLANA_DEVNET_RPC || 'https://api.devnet.solana.com',
    explorerUrl: 'https://solscan.io',
    faucetUrl: 'https://faucet.solana.com',
    isTestnet: true,
    icon: '◎',
    color: '#9945FF',
    isEVM: false,
    chainType: 'solana',
  },
  tron: {
    id: 'tron-mainnet',
    name: 'TRON Mainnet',
    shortName: 'tron',
    symbol: 'TRX',
    decimals: 6,
    rpcUrl: 'https://api.trongrid.io',
    explorerUrl: 'https://tronscan.org',
    isTestnet: false,
    icon: '◆',
    color: '#FF0013',
    isEVM: false,
    chainType: 'tron',
  },
  'tron-shasta': {
    id: 'tron-shasta',
    name: 'TRON Shasta Testnet',
    shortName: 'tron-shasta',
    symbol: 'TRX',
    decimals: 6,
    rpcUrl: 'https://api.shasta.trongrid.io',
    explorerUrl: 'https://shasta.tronscan.org',
    faucetUrl: 'https://www.trongrid.io/shasta',
    isTestnet: true,
    icon: '◆',
    color: '#FF0013',
    isEVM: false,
    chainType: 'tron',
  },
};

export const EVM_NETWORKS = Object.values(NETWORKS).filter(n => n.isEVM);
export const TESTNET_NETWORKS = Object.values(NETWORKS).filter(n => n.isTestnet);
export const MAINNET_NETWORKS = Object.values(NETWORKS).filter(n => !n.isTestnet);

export const getNetwork = (name: string): NetworkConfig | undefined => NETWORKS[name];

export const getNetworkByChainId = (chainId: number | string): NetworkConfig | undefined =>
  Object.values(NETWORKS).find(n => n.id === chainId);

export const EXPLORER_URLS: Record<string, string> = {
  ethereum: 'https://etherscan.io',
  bsc: 'https://bscscan.com',
  polygon: 'https://polygonscan.com',
  avalanche: 'https://snowtrace.io',
  arbitrum: 'https://arbiscan.io',
  optimism: 'https://optimistic.etherscan.io',
  solana: 'https://solscan.io',
  tron: 'https://tronscan.org',
};
